In [1]:
# Chạy cell này để verify optimizer sẵn sàng làm input cho dashboard
import sys
sys.path.append('../src')
from optimizer import min_variance_portfolio, display_portfolio

r = min_variance_portfolio(['VCB','VNM','HPG','FPT','MWG',
                             'BID','CTG','KDC','GAS','REE'])
display_portfolio(r, 'Demo 10 mã cho Dashboard')

=======================================================
  Demo 10 mã cho Dashboard
=======================================================
  Portfolio Return    :    8.30%
  Portfolio Volatility:   14.96%
  Sharpe Ratio        :    0.254
───────────────────────────────────────────────────────
  Equal Weights Vol   :   19.86%  (baseline)
  Volatility Reduction:    24.7%
=======================================================

  Allocation (7 active positions):
  Ticker     Weight   Exp Return
  ──────────────────────────────
  KDC         52.1%         8.1%
  VNM         17.9%        -2.6%
  VCB         13.6%         9.6%
  REE          5.6%        22.2%
  FPT          5.2%        24.8%
  GAS          4.5%        11.5%
  HPG          1.1%        14.5%
  ──────────────────────────────
  TOTAL      100.0%

  Ticker Weight% Exp Ret%
0    KDC   52.1%     8.1%
1    VNM   17.9%    -2.6%
2    VCB   13.6%     9.6%
3    REE    5.6%    22.2%
4    FPT    5.2%    24.8%
5    GAS    4.5%    11.5%
6    HPG    1.1%    14.5%

In [6]:
import sys
sys.path.append('../src')
from data_loader import update_db, load_from_db, get_db_summary

update_db(start='2021-01-01', replace=False)

✅ Table Stock_Prices ready
📥 Fetching 30 tickers | 2021-01-01 → 2026-04-21
   Source: vnstock3 VCI (fallback: yfinance)

  ⚠️  VCB   →     0 rows
  ⚠️  BID   →     0 rows
  ⚠️  CTG   →     0 rows
  ⚠️  TCB   →     0 rows
  ⚠️  MBB   →     0 rows
  ⚠️  VPB   →     0 rows
  ⚠️  ACB   →     0 rows
  ⚠️  HDB   →     0 rows
  ⚠️  STB   →     0 rows
  ⚠️  SHB   →     0 rows
  ⚠️  LPB   →     0 rows
  ⚠️  OCB   →     0 rows

2026-04-21 20:18:34 - vnstock3.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Read timed out.

  ⚠️  VCI error [MSB]: ConnectionError: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443)
  → Fallback to yfinance for MSB
  ⚠️  MSB   →     0 rows
  ⚠️  EIB   →     0 rows
  ⚠️  VIC   →     0 rows
  ⚠️  VHM   →     0 rows
  ⚠️  VRE   →     0 rows
  ⚠️  FPT   →     0 rows
  ⚠️  VNM   →     0 rows
  ⚠️  MWG   →     0 rows
  ⚠️  SAB   →     0 rows
  ⚠️  GAS   →     0 rows
  ⚠️  PLX   →     0 rows
  ⚠️  HPG   →     0 rows
  ⚠️  BVH   →     0 rows
  ⚠️  HVN   →     0 rows
  ⚠️  GMD   →     0 rows

2026-04-21 20:20:51 - vnstock3.core.utils.client - ERROR - API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443): Read timed out. (read timeout=30)

  ⚠️  VCI error [PDR]: ConnectionError: API request failed: HTTPSConnectionPool(host='trading.vietcap.com.vn', port=443)
  → Fallback to yfinance for PDR
  ⚠️  PDR   →     0 rows
  ⚠️  KDC   →     0 rows
  ⚠️  REE   →     0 rows

✅ Done. Total new rows: 0

📊 DB Summary:
Ticker  rows start_date   end_date
   ACB  1319 2021-01-04 2026-04-21
   BID  1319 2021-01-04 2026-04-21
   BVH  1319 2021-01-04 2026-04-21
   CTG  1319 2021-01-04 2026-04-21
   EIB  1319 2021-01-04 2026-04-21
   FPT  1319 2021-01-04 2026-04-21
   GAS  1319 2021-01-04 2026-04-21
   GMD  1319 2021-01-04 2026-04-21
   HDB  1319 2021-01-04 2026-04-21
   HPG  1319 2021-01-04 2026-04-21
   HVN  1319 2021-01-04 2026-04-21
   KDC  1319 2021-01-04 2026-04-21
   LPB  1319 2021-01-04 2026-04-21
   MBB  1319 2021-01-04 2026-04-21
   MSB  1319 2021-01-04 2026-04-21
   MWG  1319 2021-01-04 2026-04-21
   OCB  1301 2021-01-28 2026-04-21
   PDR  1319 2021-01-04 2026-04-21
   PLX  1319 2021-01-04 2026-04-21
   REE  1319 2021-01-04 2026-04-21
   SAB  1319 2021-01-04 2026-04-21
   SHB  1316 2021-01-04 2026-04-21
   STB  1319 2021-01-04 2026-04-21
   TCB  1319 2021-01-04 2026-04-21
   VCB  1319 2021-01-04 2026-04-21
   VHM  1319 2021-01-04 2026-04-21
   VIC  1319 2021-01-04 2026-04-21
   VNM  1319 2021-01-04 2026-04-21
   VPB  1319 2021-01-04 2026-04-21
   VRE  1319 2021-01-04 2026-04-21

In [7]:
import sys
sys.path.append('../src')
from data_loader import update_db, load_from_db, get_db_summary
get_db_summary()

   Ticker  rows  start_date    end_date
0     ACB  1319  2021-01-04  2026-04-21
1     BCM  1319  2021-01-04  2026-04-21
2     BID  1319  2021-01-04  2026-04-21
3     BVH  1319  2021-01-04  2026-04-21
4     CTG  1319  2021-01-04  2026-04-21
5     DGC  1319  2021-01-04  2026-04-21
6     EIB  1319  2021-01-04  2026-04-21
7     FPT  1319  2021-01-04  2026-04-21
8     GAS  1319  2021-01-04  2026-04-21
9     GMD  1319  2021-01-04  2026-04-21
10    GVR  1319  2021-01-04  2026-04-21
11    HDB  1319  2021-01-04  2026-04-21
12    HPG  1319  2021-01-04  2026-04-21
13    HVN  1319  2021-01-04  2026-04-21
14    KDC  1319  2021-01-04  2026-04-21
15    LPB  1319  2021-01-04  2026-04-21
16    MBB  1319  2021-01-04  2026-04-21
17    MSB  1319  2021-01-04  2026-04-21
18    MSN  1319  2021-01-04  2026-04-21
19    MWG  1319  2021-01-04  2026-04-21
20    OCB  1301  2021-01-28  2026-04-21
21    PDR  1319  2021-01-04  2026-04-21
22    PLX  1319  2021-01-04  2026-04-21
23    REE  1319  2021-01-04  2026-04-21
24    SAB  1319  2021-01-04  2026-04-21
25    SHB  1316  2021-01-04  2026-04-21
26    SSB  1267  2021-03-24  2026-04-21
27    SSI  1319  2021-01-04  2026-04-21
28    STB  1319  2021-01-04  2026-04-21
29    TCB  1319  2021-01-04  2026-04-21
30    TPB  1319  2021-01-04  2026-04-21
31    VCB  1319  2021-01-04  2026-04-21
32    VHM  1319  2021-01-04  2026-04-21
33    VIB  1319  2021-01-04  2026-04-21
34    VIC  1319  2021-01-04  2026-04-21
35    VJC  1319  2021-01-04  2026-04-21
36    VNM  1319  2021-01-04  2026-04-21
37    VPB  1319  2021-01-04  2026-04-21
38    VPL   237  2025-05-13  2026-04-21
39    VRE  1319  2021-01-04  2026-04-21